transaction_mapping_dict = {
    'Acquisition': 'Acquisition/Purchase of Shares',
    'Purchase': 'Acquisition/Purchase of Shares',
    'Kjøp': 'Acquisition/Purchase of Shares',
    'disposed': 'Disposal/Sale of Shares',
    'Subscription of shares': 'Acquisition/Purchase of Shares',
    'Sale': 'Disposal/Sale of Shares',
    'Lending of shares': 'Lending/Pledging/Agreement',
    'Allocation of shares in rights issue': 'Acquisition/Purchase of Shares',
    'Salg': 'Disposal/Sale of Shares',
    'Sale of shares': 'Disposal/Sale of Shares',
    'Purchase of shares': 'Acquisition/Purchase of Shares',
    'Exercise of options with cash settlement': 'Cash Settlement of Rights/Options',
    'Acquisition of shares': 'Acquisition/Purchase of Shares',
    'Grant of options': 'Grant/Award of Rights/Instruments',
    'Exercise of warrants': 'Exercise/Settlement leading to Shares',
    'Acquired': 'Acquisition/Purchase of Shares',
    'Internal transfer of shares': 'Transfer (Internal/Other)',
    'exercise of options': 'Exercise/Settlement leading to Shares',
    'buyback': 'Share Buyback/Repurchase',
    'BUYBACK': 'Share Buyback/Repurchase',
    'purchase': 'Acquisition/Purchase of Shares',
    'Grant of Options': 'Grant/Award of Rights/Instruments',
    'acquisition': 'Acquisition/Purchase of Shares',
    'share buyback': 'Share Buyback/Repurchase',
    'share buyback program': 'Share Buyback/Repurchase',
    'Share buyback': 'Share Buyback/Repurchase',
    'Grant': 'Grant/Award of Rights/Instruments',
    'Exercise of options and transfer of rights': 'Transfer (Rights)',
    'Exercise of options (settled in cash)': 'Cash Settlement of Rights/Options',
    'Received shares from RSUs': 'Acquisition/Purchase of Shares',
    'Holding shares': 'Administrative/Other/No Transaction',
    'issuance of new shares': 'Acquisition/Purchase of Shares',
    'Accepted offer': 'Acquisition/Purchase of Shares',
    'Not specified': 'Administrative/Other/No Transaction',
    'Exercise of options and sale': 'Exercise and Sale (Net Disposal)',
    'Exercise of options': 'Exercise/Settlement leading to Shares',
    'Transfer': 'Transfer (Internal/Other)',
    'Exercise of Options': 'Exercise/Settlement leading to Shares',
    'Transfer of Rights': 'Transfer (Rights)',
    'Demerger/transfer of shares': 'Transfer (Outflow/Internal)',
    'Receipt of demerged shares': 'Acquisition/Purchase of Shares',
    'Tildeling': 'Acquisition/Purchase of Shares',
    'Buy': 'Acquisition/Purchase of Shares',
    'Transfer to associated company': 'Transfer (Outflow/Internal)',
    'Transfer from associated person': 'Acquisition/Purchase of Shares',
    'Gave gitt': 'Disposal/Sale of Shares',
    'Gave mottatt': 'Acquisition/Purchase of Shares',
    'Tildeling (Bonus)': 'Acquisition/Purchase of Shares',
    'Overdragelse': 'Transfer (Internal/Other)',
    'Tildeling av bonusaksjer': 'Acquisition/Purchase of Shares',
    'gave': 'Acquisition/Purchase of Shares',
    'Award': 'Acquisition/Purchase of Shares',
    'Kj\\': 'Unclassified/Needs Review',
    'Sold': 'Disposal/Sale of Shares',
    'Salg av egne aksjer': 'Disposal/Sale of Shares',
    'sale': 'Disposal/Sale of Shares',
    'salg': 'Disposal/Sale of Shares',
    'Awarded shares': 'Acquisition/Purchase of Shares',
    'Sold shares': 'Disposal/Sale of Shares',
    'Awarded': 'Acquisition/Purchase of Shares',
    'Awarded shares as part of remuneration program': 'Acquisition/Purchase of Shares',
    'Aksjetildeling som del av aksjelønnsprogram': 'Acquisition/Purchase of Shares',
    'Tildelt': 'Acquisition/Purchase of Shares',
    'Tildelt aksjer': 'Acquisition/Purchase of Shares',
    'Sale of forward contracts': 'Disposal of Rights/Instruments',
    'Ikke oppgitt': 'Administrative/Other/No Transaction',
    'Forward contract': 'Lending/Pledging/Agreement',
    'TRS agreement extended': 'Administrative/Other/No Transaction',
    'TRS Agreement Extension': 'Administrative/Other/No Transaction',
    'Forward contract extension': 'Administrative/Other/No Transaction',
    'TRS agreement': 'Lending/Pledging/Agreement',
    'Acquired forward contract': 'Acquisition of Rights/Instruments',
    'Acquired forward contracts': 'Acquisition of Rights/Instruments',
    'Acquired shares': 'Acquisition/Purchase of Shares',
    'Awarded as remuneration/bonus': 'Acquisition/Purchase of Shares',
    'Receipt of ordinary shares in Solstad Maritime ASA as dividend-in-kind from AMSC ASA (under liquidation)': 'Acquisition/Purchase of Shares',
    'Assumption of shares': 'Acquisition/Purchase of Shares',
    'Subscription': 'Acquisition/Purchase of Shares',
    'Exercise of subscription rights': 'Exercise/Settlement leading to Shares',
    'Sale of subscription rights': 'Disposal of Rights/Instruments',
    'Exercise of share purchase option': 'Exercise/Settlement leading to Shares',
    'allocation of rights': 'Grant/Award of Rights/Instruments',
    'acquired': 'Acquisition/Purchase of Shares',
    'Disposal': 'Disposal/Sale of Shares',
    'Grant of share options': 'Grant/Award of Rights/Instruments',
    'Lending': 'Lending/Pledging/Agreement',
    'Not applicable': 'Administrative/Other/No Transaction',
    'Share lending': 'Lending/Pledging/Agreement',
    'Pledging': 'Lending/Pledging/Agreement',
    'Transfer of shares': 'Transfer (Internal/Other)',
    'Redelivery of shares lent': 'Lending/Pledging/Agreement',
    'Grant of Share Options': 'Grant/Award of Rights/Instruments',
    'Share Consolidation': 'Administrative/Other/No Transaction',
    'Award of Restricted Share Units': 'Grant/Award of Rights/Instruments',
    'Exercise of RSUs and transfer of shares': 'Exercise/Settlement leading to Shares',
    'Award of Share Options': 'Grant/Award of Rights/Instruments',
    'Acquisition of Shares': 'Acquisition/Purchase of Shares',
    'Exercise': 'Exercise/Settlement leading to Shares',
    'Purchase of Shares': 'Acquisition/Purchase of Shares',
    'buy': 'Acquisition/Purchase of Shares',
    'Grant of Restricted Share Units': 'Grant/Award of Rights/Instruments',
    'grant of share options': 'Grant/Award of Rights/Instruments',
    'Acquired subscription rights': 'Acquisition of Rights/Instruments',
    'Annen transaksjonstype': 'Administrative/Other/No Transaction',
    'Subscription Rights': 'Acquisition of Rights/Instruments',
    'Acquisition of options to share': 'Acquisition of Rights/Instruments',
    'Exercise of share option': 'Exercise/Settlement leading to Shares',
    'Exercise of share option and subsequent sale': 'Exercise and Sale (Net Disposal)',
    'Tildeling av opsjoner': 'Grant/Award of Rights/Instruments',
    'Exercise of share option and Purchase': 'Exercise/Settlement leading to Shares',
    'Option Grant': 'Grant/Award of Rights/Instruments',
    'Exercise of stock option': 'Exercise/Settlement leading to Shares',
    'exercise of stock options': 'Exercise/Settlement leading to Shares',
    'sale of shares': 'Disposal/Sale of Shares',
    'Exercise of stock options': 'Exercise/Settlement leading to Shares',
    'repurchase of own shares': 'Share Buyback/Repurchase',
    'Acquisition of options': 'Acquisition of Rights/Instruments',
    'share repurchase': 'Share Buyback/Repurchase',
    'Share repurchase': 'Share Buyback/Repurchase',
    'Opsjonsutstedelse': 'Grant/Award of Rights/Instruments',
    'Receipt of shares pursuant to a capital reduction': 'Acquisition/Purchase of Shares',
    'Disposal/transfer of shares pursuant to a capital reduction': 'Transfer (Outflow/Internal)',
    'Return of lent shares': 'Lending/Pledging/Agreement',
    'Lending out shares': 'Lending/Pledging/Agreement',
    'Subscription (Acquisition)': 'Acquisition/Purchase of Shares',
    'Subscription/receipt': 'Acquisition/Purchase of Shares',
    'Subscription of new shares': 'Acquisition/Purchase of Shares',
    'Share lending agreement - re-delivery': 'Lending/Pledging/Agreement',
    'Tegning': 'Acquisition/Purchase of Shares',
    'subscription': 'Acquisition/Purchase of Shares',
    'Grant of restricted stock units': 'Grant/Award of Rights/Instruments',
    'Grant of shares': 'Acquisition/Purchase of Shares',
    'Employee Share Saving Plan': 'Acquisition/Purchase of Shares',
    'Bonus matching shares': 'Acquisition/Purchase of Shares',
    'Grant of Restricted Stock Units': 'Grant/Award of Rights/Instruments',
    'Grant of Restricted Stock Units (RSUs)': 'Grant/Award of Rights/Instruments',
    'Aksept av aksjeopsjon': 'Grant/Award of Rights/Instruments',
    'Subscription to Employee Share Saving Plan': 'Acquisition/Purchase of Shares',
    'Received': 'Acquisition/Purchase of Shares',
    'Other': 'Administrative/Other/No Transaction',
    'Grant of shares under LTIP': 'Acquisition/Purchase of Shares',
    'Grant of restricted shares': 'Acquisition/Purchase of Shares',
    'Subscription to employee share saving plan': 'Acquisition/Purchase of Shares',
    'sell': 'Disposal/Sale of Shares',
    'Buyback': 'Share Buyback/Repurchase',
    'Allotment': 'Acquisition/Purchase of Shares',
    'Tildeling av aksjer': 'Acquisition/Purchase of Shares',
    'Reinvestment': 'Administrative/Other/No Transaction',
    'Tegning (aksjespareprogram)': 'Acquisition/Purchase of Shares',
    'Aksjespareprogram': 'Acquisition/Purchase of Shares',
    'Acceptance of share option': 'Grant/Award of Rights/Instruments',
    'Subscription of new shares (allocation in private placement)': 'Acquisition/Purchase of Shares',
    'transfer of rights to receive shares': 'Transfer (Rights)',
    'Share sale': 'Disposal/Sale of Shares',
    'Share subscription': 'Acquisition/Purchase of Shares',
    'Grant of LTI Options': 'Grant/Award of Rights/Instruments',
    'kjøp': 'Acquisition/Purchase of Shares',
    'Pledge': 'Lending/Pledging/Agreement',
    'Sale of share options': 'Disposal of Rights/Instruments',
    'Distribution': 'Acquisition/Purchase of Shares',
    'Receipt': 'Acquisition/Purchase of Shares',
    'Investment': 'Acquisition/Purchase of Shares',
    'SHARE PURCHASE': 'Acquisition/Purchase of Shares',
    'Share Purchase': 'Acquisition/Purchase of Shares',
    'Stock purchase': 'Acquisition/Purchase of Shares',
    'Stock Purchase': 'Acquisition/Purchase of Shares',
    'Acceptance of share options': 'Grant/Award of Rights/Instruments',
    'transfer': 'Transfer (Internal/Other)',
    'Not Applicable': 'Administrative/Other/No Transaction',
    'Grant of share option': 'Grant/Award of Rights/Instruments',
    'exercise of share options and sale by third party': 'Exercise and Sale (Net Disposal)',
    'Exercise of options and sale of shares': 'Exercise and Sale (Net Disposal)',
    'Application for offer shares': 'Acquisition/Purchase of Shares',
    'Allocation of options': 'Grant/Award of Rights/Instruments',
    'allocation': 'Acquisition/Purchase of Shares',
    'Overføring til heleid selskap': 'Transfer (Outflow/Internal)',
    'Kjøp av rettigheter': 'Acquisition of Rights/Instruments',
    'Tegning i spareordning': 'Acquisition/Purchase of Shares',
    'tegning i spareordning': 'Acquisition/Purchase of Shares',
    'tildeling i ansatteemisjon': 'Acquisition/Purchase of Shares',
    'reparasjonsemisjon': 'Acquisition/Purchase of Shares',
    'tildeling i reparasjonsemisjonen': 'Acquisition/Purchase of Shares',
    'Award of warrants': 'Grant/Award of Rights/Instruments',
    'No Transaction': 'Administrative/Other/No Transaction',
    'subscribed': 'Acquisition/Purchase of Shares',
    'Purchase of debt instruments': 'Acquisition of Rights/Instruments',
    'sale of debt instruments': 'Disposal of Rights/Instruments',
    'Sale/transfer of debt instruments': 'Disposal of Rights/Instruments',
    'Acquisition/receipt of debt instruments': 'Acquisition of Rights/Instruments',
    'Subscription of warrants': 'Acquisition of Rights/Instruments',
    'Share lending and re-delivery': 'Lending/Pledging/Agreement',
    'Amendment of existing share options': 'Administrative/Other/No Transaction',
    'Granting/acceptance of share options': 'Grant/Award of Rights/Instruments',
    'Sell': 'Disposal/Sale of Shares',
    'Allocation': 'Acquisition/Purchase of Shares',
    'Allocation of equity capital certificates': 'Acquisition/Purchase of Shares',
    'Inheritance received': 'Acquisition/Purchase of Shares',
    'Arv mottatt': 'Acquisition/Purchase of Shares',
    'overført': 'Transfer (Internal/Other)',
    'Overføring av tegningsrettigheter': 'Transfer (Rights)',
    'Intra-group transfer of shares': 'Transfer (Internal/Other)',
    'Subscription of Fee Shares': 'Acquisition/Purchase of Shares',
    'Subscription of shares in rights issue': 'Acquisition/Purchase of Shares',
    'Grant of warrants': 'Grant/Award of Rights/Instruments',
    'Subscription of shares in private placement': 'Acquisition/Purchase of Shares',
    'Gift to children via MTB Invest AS': 'Transfer (Outflow/Internal)',
    'Sale to brother': 'Disposal/Sale of Shares',
    'Gavedisposisjon': 'Disposal/Sale of Shares',
    'Opsjon tildelt': 'Grant/Award of Rights/Instruments',
    'Aksjetegning': 'Acquisition/Purchase of Shares',
    'Conversion of bond loan': 'Acquisition/Purchase of Shares',
    'Acquisition of own shares from subsidiary': 'Acquisition/Purchase of Shares',
    'Bought shares': 'Acquisition/Purchase of Shares',
    'Purchase not completed': 'Administrative/Other/No Transaction',
    'Transfer of additional bonus shares': 'Transfer (Internal/Other)',
    'Transfer of bonus shares': 'Transfer (Internal/Other)',
    'Allocation and delivery of bonus shares': 'Acquisition/Purchase of Shares',
    'Sales of shares': 'Disposal/Sale of Shares',
    'Share Lending': 'Lending/Pledging/Agreement',
    'Pledge of shares': 'Lending/Pledging/Agreement',
    'Exercise of options (cashless)': 'Exercise/Settlement leading to Shares',
    'Kjøpt': 'Acquisition/Purchase of Shares',
    'Tildelt, Kjøpt, Solgt': 'Mixed/Multiple Transaction Type',
    'Tildelt, Kjøpt': 'Mixed/Multiple Transaction Type',
    'Salg av tegningsretter': 'Disposal of Rights/Instruments',
    'Receiving shares in Aker ASA as merger consideration': 'Acquisition/Purchase of Shares',
    'bonus shares': 'Acquisition/Purchase of Shares',
    'Subscription to convertible loan': 'Acquisition/Purchase of Shares',
    'Sale of real estate assets': 'Disposal/Sale of Shares',
    'Salgsordre': 'Disposal/Sale of Shares',
    'Internal Transfer': 'Transfer (Internal/Other)',
    'Grant share options': 'Grant/Award of Rights/Instruments',
    'Acceptance of a stock option': 'Grant/Award of Rights/Instruments',
    'Allocation of shares': 'Acquisition/Purchase of Shares',
    'Extension of exercise period for share options': 'Administrative/Other/No Transaction',
    'Share option replacement': 'Administrative/Other/No Transaction',
    'Share option expiry date extension': 'Administrative/Other/No Transaction',
    'Share option grant': 'Grant/Award of Rights/Instruments',
    'Subscription of shares in a rights issue': 'Acquisition/Purchase of Shares',
    'Share option extension': 'Administrative/Other/No Transaction',
    'Shares received as settlement of a share loan': 'Acquisition/Purchase of Shares',
    'Share Lending Redelivery': 'Lending/Pledging/Agreement',
    'Lend Out': 'Lending/Pledging/Agreement',
    'Lend out': 'Lending/Pledging/Agreement',
    'grant': 'Grant/Award of Rights/Instruments',
    'exercise of share options': 'Exercise/Settlement leading to Shares',
    'Grant of new share options': 'Grant/Award of Rights/Instruments',
    'exercise of warrants': 'Exercise/Settlement leading to Shares',
    'Exercise of employee options': 'Exercise/Settlement leading to Shares',
    'Restricted stock units konvertert til aksjer': 'Exercise/Settlement leading to Shares',
    'Tildelte RSU`er ifm aksjeprogram': 'Grant/Award of Rights/Instruments',
    'Restricted stock units issued by company': 'Grant/Award of Rights/Instruments',
    'Tildeling av aksjer som en del av RSU program': 'Acquisition/Purchase of Shares',
    'Restricted stock units granted': 'Grant/Award of Rights/Instruments',
    'Settlement of Restricted Stock Units': 'Exercise/Settlement leading to Shares',
    'Bought': 'Acquisition/Purchase of Shares',
    'Grant of RSUs': 'Grant/Award of Rights/Instruments',
    'Overføring': 'Transfer (Internal/Other)',
    'bought': 'Acquisition/Purchase of Shares',
    'Tegnet seg for aksjer': 'Acquisition/Purchase of Shares',
    'Settlement of forward contract': 'Exercise/Settlement leading to Shares',
    'Delinnløsning av terminkontrakt': 'Lending/Pledging/Agreement',
    'Recalculation of forward contracts': 'Administrative/Other/No Transaction',
    'Forward contract recalculation': 'Administrative/Other/No Transaction',
    'Extension of forward contract': 'Administrative/Other/No Transaction',
    'Sale and Purchase': 'Mixed/Multiple Transaction Type',
    'Donasjon': 'Disposal/Sale of Shares',
    'Recalculation of forward contract price': 'Administrative/Other/No Transaction',
    'Extension of forward contracts': 'Administrative/Other/No Transaction',
    'forward agreement': 'Lending/Pledging/Agreement',
    'Acceptance of stock option': 'Grant/Award of Rights/Instruments',
    'Exercise of share options and sale': 'Exercise and Sale (Net Disposal)',
    'proxy': 'Administrative/Other/No Transaction',
    'Salg av rettigheter': 'Disposal of Rights/Instruments',
    'tegnet egenkapitalbevis ved utøvelse av tegningsretter': 'Exercise/Settlement leading to Shares',
    'tegnet egenkapitalbevis': 'Acquisition/Purchase of Shares',
    'tegnet': 'Acquisition/Purchase of Shares',
    'Aksjeopsjon': 'Grant/Award of Rights/Instruments',
    'Share exchange': 'Acquisition/Purchase of Shares',
    'Forward purchase agreement': 'Lending/Pledging/Agreement',
    'Settlement of synthetic shares': 'Cash Settlement of Rights/Options',
    'Erverv av aksjeopsjon': 'Acquisition of Rights/Instruments',
    'Overføring av aksjer': 'Transfer (Internal/Other)',
    'Grant of stock option': 'Grant/Award of Rights/Instruments',
    'Share purchase': 'Acquisition/Purchase of Shares',
    'Allocation of shares as an underwriter': 'Acquisition/Purchase of Shares',
    'Subscription for shares and exercise of subscription rights': 'Acquisition/Purchase of Shares',
    'Grant of PSUs': 'Grant/Award of Rights/Instruments',
    'Subscription for shares': 'Acquisition/Purchase of Shares',
    'Re-delivery of shares lent out': 'Lending/Pledging/Agreement',
    'Shares lent out': 'Lending/Pledging/Agreement',
    'Award of Performance Share Unit (PSU)': 'Grant/Award of Rights/Instruments',
    'Subscription of convertible loan': 'Acquisition/Purchase of Shares',
    'Purchase of call options': 'Acquisition of Rights/Instruments',
    'Receipt of options': 'Acquisition of Rights/Instruments',
    'Warrant exercise': 'Exercise/Settlement leading to Shares',
    'Grant of Incentive Subscription Rights': 'Grant/Award of Rights/Instruments',
    'Other transaction type': 'Administrative/Other/No Transaction',
    'Aksjeopsjonsprogram': 'Grant/Award of Rights/Instruments',
    'Overdragelse til datterselskap': 'Transfer (Outflow/Internal)',
    'Overdragelse til barnas selskaper': 'Transfer (Outflow/Internal)',
    'Subscription for Common Shares': 'Acquisition/Purchase of Shares',
    'Granting of stock options': 'Grant/Award of Rights/Instruments',
    'Received shares': 'Acquisition/Purchase of Shares',
    'subscription rights': 'Acquisition of Rights/Instruments',
    'receipt of subscription rights': 'Acquisition of Rights/Instruments',
    'Conversion of convertible bonds into shares': 'Acquisition/Purchase of Shares',
    'Exercise of share options and transfer to close associate': 'Exercise/Settlement leading to Shares',
    'Sale of shares by close associate to cover strike price and tax expenses': 'Disposal/Sale of Shares',
    'Distribution of shares as liquidation dividend': 'Disposal/Sale of Shares',
    'Sale of Subscription Rights': 'Disposal of Rights/Instruments',
    'Acquisition of ordinary shares': 'Acquisition/Purchase of Shares',
    'Granting/acceptance of options': 'Grant/Award of Rights/Instruments',
    'Granting/acceptance of PSUs': 'Grant/Award of Rights/Instruments',
    'Conversion of share options to cash bonus': 'Cash Settlement of Rights/Options',
    'Cash settlement of stock option': 'Cash Settlement of Rights/Options',
    'Exercise of synthetic options': 'Cash Settlement of Rights/Options',
    'Mottak av aksjer som del av styrehonorar': 'Acquisition/Purchase of Shares',
    'Exercise of employee options (settled in cash)': 'Cash Settlement of Rights/Options',
    'Subscription of Incentive Subscription Rights': 'Acquisition/Purchase of Shares',
    'Exercise of share options': 'Exercise/Settlement leading to Shares',
    'Return of shares lent out': 'Lending/Pledging/Agreement',
    'Gift - given': 'Disposal/Sale of Shares',
    'Gift - received': 'Acquisition/Purchase of Shares',
    'dividend-in-kind': 'Acquisition/Purchase of Shares',
    'Settlement of RSUs': 'Exercise/Settlement leading to Shares',
    'Subscription of share in Private placement': 'Acquisition/Purchase of Shares',
    'Exercise of rights': 'Exercise/Settlement leading to Shares',
    'Redelivery of shares under a share lending agreement': 'Lending/Pledging/Agreement',
    'Utlån': 'Lending/Pledging/Agreement',
    'Lån': 'Lending/Pledging/Agreement',
    'return of lent shares': 'Lending/Pledging/Agreement',
    'cash settlement': 'Cash Settlement of Rights/Options',
    'settlement': 'Exercise/Settlement leading to Shares',
    'Settlement of restricted stock units': 'Exercise/Settlement leading to Shares',
    'Receipt of shares': 'Acquisition/Purchase of Shares',
    'exercise': 'Exercise/Settlement leading to Shares',
    'Grant of stock options': 'Grant/Award of Rights/Instruments',
    'Granting/accepting of share options': 'Grant/Award of Rights/Instruments',
    'Share Purchase from capital increase': 'Acquisition/Purchase of Shares',
    'Exercise of share options with cash settlement': 'Cash Settlement of Rights/Options',
    'Exercise of employee share option program with cash settlement': 'Cash Settlement of Rights/Options',
    'Exercise of options in cash settlement': 'Cash Settlement of Rights/Options',
    'Acquisition of Warrants': 'Acquisition of Rights/Instruments',
    'Matching shares under 2023 ESPP vested and transferred free of charge': 'Acquisition/Purchase of Shares',
    'Acceptance of shares allocated and delivered in a subsequent offering': 'Acquisition/Purchase of Shares',
    'Option award': 'Grant/Award of Rights/Instruments',
    'Subscription of ordinary shares': 'Acquisition/Purchase of Shares',
    'Subscription of Guarantee Shares': 'Acquisition/Purchase of Shares',
    'Sale of ordinary shares': 'Disposal/Sale of Shares',
    'settlement of options/incentives': 'Exercise/Settlement leading to Shares',
    'Utøvelse av rettigheter': 'Exercise/Settlement leading to Shares',
    'Gift': 'Acquisition/Purchase of Shares',
    'Issue': 'Acquisition/Purchase of Shares',
    'Shares to be lent out to facilitate settlement of a private placement': 'Lending/Pledging/Agreement',
    'Awarded options': 'Grant/Award of Rights/Instruments',
    'Subscription for shares in a subsequent offering': 'Acquisition/Purchase of Shares',
    'Extension of expiry date of share options': 'Administrative/Other/No Transaction',
    'Sale of ordinary shares in Solstad Maritime ASA to cover withholding tax': 'Disposal/Sale of Shares',
    'Subscription of shares in the subsequent offering': 'Acquisition/Purchase of Shares',
    'Not disclosed': 'Administrative/Other/No Transaction',
    'Disposal of shares': 'Disposal/Sale of Shares',
    'Acquisition of warrants': 'Acquisition of Rights/Instruments',
    'Award of synthetic shares': 'Grant/Award of Rights/Instruments',
    'Automatic cash settlement of synthetic shares': 'Cash Settlement of Rights/Options',
    'Application for Offer Shares': 'Acquisition/Purchase of Shares',
    'Provisional award of PSUs': 'Grant/Award of Rights/Instruments',
    'Disposal/transfer': 'Transfer (Outflow/Internal)',
    'Granting of treasury shares': 'Acquisition/Purchase of Shares',
    'application for Offer Shares': 'Acquisition/Purchase of Shares',
    'Return of borrowed shares': 'Lending/Pledging/Agreement',
    'Granting of share options': 'Grant/Award of Rights/Instruments',
    'cash settlement of synthetic shares': 'Cash Settlement of Rights/Options',
    'Allocation of shares under long term incentive program': 'Acquisition/Purchase of Shares',
    'transfer to own holding company': 'Transfer (Internal/Other)',
    'Salg av aksjer': 'Disposal/Sale of Shares',
    'Kjøp av egne aksjer': 'Share Buyback/Repurchase',
    'Kjøp av tegningsretter': 'Acquisition of Rights/Instruments',
    'Tegning av nye egenkapitalbevis': 'Acquisition/Purchase of Shares',
    'tegning av nye egenkapitalbevis': 'Acquisition/Purchase of Shares',
    'kjøp av tegningsretter': 'Acquisition of Rights/Instruments',
    'overføring': 'Transfer (Internal/Other)',
    'Receipt of subscription rights': 'Acquisition of Rights/Instruments',
    'Tegne aksjer': 'Acquisition/Purchase of Shares',
    'Innløsing av opsjoner': 'Exercise/Settlement leading to Shares',
    'call of stock options': 'Exercise/Settlement leading to Shares',
    'Right Issue': 'Acquisition/Purchase of Shares',
    'Distribution in specie': 'Acquisition/Purchase of Shares',
    'bonus': 'Acquisition/Purchase of Shares',
    'Tildeling (bonus)': 'Acquisition/Purchase of Shares',
    'Conversion of stock options to cash bonus': 'Cash Settlement of Rights/Options',
    'Conversion of share options to cash consideration': 'Cash Settlement of Rights/Options',
    'Allocation of incentive share options': 'Grant/Award of Rights/Instruments',
    'option grant': 'Grant/Award of Rights/Instruments',
    'not specified': 'Administrative/Other/No Transaction',
    'Subscription in rights issue': 'Acquisition/Purchase of Shares',
    'BUY': 'Acquisition/Purchase of Shares',
    'Forward Contract Settlement': 'Exercise/Settlement leading to Shares'
}